name: SSH Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build angular app
        working-directory: client
        run: |
              npm ci
              npm run build
      - name: Create cgi-bin
        working-directory: client/build/client
        run: mkdir cgi-bin
      - name: ssh deploy client
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          privateKey: ${{ secrets.DEPLOY_KEY }}
          dotfiles: true
          rmRemote: true
          local: client/build/client/
          remote: domains/thibautdemaerteleire.be/public_html/footy


  server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build prod laravel
        working-directory: server
        run: |
              npm install
              npm run production
      - name: Create cgi-bin and .env
        working-directory: server
        run: |
              mkdir cgi-bin
              touch .env
              echo ${{ secrets.LARAVEL_ENV_KEYS }} >> .env
              cat .env
      - name: Remove folders
        working-directory: server
        run: |
              rm -rf node_modules
              rm -rf vendor
              ls
      - name: Remove vendor from ssh server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
                    cd domains/thibautdemaerteleire.be/public_html/api.footy
                    rm -rf *
                    ls

      - name: ssh deploy laravel server api
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          privateKey: ${{ secrets.DEPLOY_KEY }}
          dotfiles: true
          local: server/
          remote: domains/thibautdemaerteleire.be/public_html/api.footy
      
      - name: Build laravel composer app/api on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
                    cd 'domains/thibautdemaerteleire.be/public_html/api.footy'
                    composer install --prefer-dist --no-interaction --no-suggest
  
  storybook:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build storybook
        working-directory: client
        run: |
              npm ci
              npm run build-storybook
      - name: Create cgi-bin
        working-directory: client/build/storybook
        run: mkdir cgi-bin        
      - name: ssh deploy storybook
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          privateKey: ${{ secrets.DEPLOY_KEY }}
          dotfiles: true
          rmRemote: true
          local: client/build/storybook/
          remote: domains/thibautdemaerteleire.be/public_html/storybook.footy